%this code runs your analysis script 
%NEVER just "Run" this code, it must be run in SECTIONS depending on your
%needs, if you just "Run" this code you will overwrite any pulses you
%analyze and it will keep running each section until the end or it throws
%an error 

%To run this code you must have already preprocessed your data file,
% through preprocessing you will generate the files you require to run this 
% specifically the following files (generated by the preprocessing code
% must already be in your workspace: 
% yasls= the fit baseline
% ydetrend= the detrended data (data-baseline) 
% yas3det= the most smoothed detrended data
% yas2det= a "medium" smoothed detrended data
% stderror = the signal noise 

%% Run this section if you've just started- no figures up, starting from the beginning 


if exist('dmin','var') ~=1
    dmin=input('dmin is not saved in your workspace, type what you want dmin to be right now');
end
if exist('plot_thresh','var') ~=1
    plot_thresh=0;
end
en=1;
% run if no figures are up (automatically starts from the beginning) 

[pulses,threshpts,fig_handles]=mznps_pickpulse_semiauto_nodownsamp(ydetrend,yasls,yas2det,dmin,stderror,yas3det,plot_thresh,0,0,0,en);

%% run if your figures are NOT already up- but you want to start from where you left off 
if exist('dmin','var') ~=1
    dmin=input('dmin is not saved in your workspace, type what you want dmin to be right now');
end
if exist('plot_thresh','var') ~=1
    plot_thresh=0;
end
en=1;
%if you copied and pasted the pulses as a new variable there needs to be at
%least one row of zeros at the end - so lets add one..
numpulses=length(pulses(:,1));
pulses(numpulses+1,:)=zeros(1,length(pulses(1,:)));
numpulses=numpulses+1;
i=2;
while i<=numpulses
    if pulses(i,1)==0
        i=i-1;
        skipto=pulses(i,1);
        break
    else
        i=i+1;
    end
end
[pulses,threshpts,fig_handles]=mznps_pickpulse_semiauto_nodownsamp(ydetrend,yasls,yas2det,dmin,stderror,yas3det,plot_thresh,skipto,0,0,en);


%% run if your figures are already up and you want to start from the beginning 
use_old_fig=1;
skipto=0;
[pulses,threshpts,fig_handles]=mznps_pickpulse_semiauto_nodownsamp(ydetrend,yasls,yas2det,dmin,stderror,yas3det,plot_thresh,skipto,use_old_fig,fig_handles,en);

%% run if your figures are already up and you want to start from where you left off
use_old_fig=1;
i=2;
while i<=length(pulses(:,1))
    if pulses(i,1)==0
        i=i-1;
        skipto=pulses(i,1);
        break
    else
        i=i+1;
    end
end

[pulses,threshpts,fig_handles]=mznps_pickpulse_semiauto_nodownsamp(ydetrend,yasls,yas2det,dmin,stderror,yas3det,plot_thresh,skipto,use_old_fig,fig_handles,en);

%% run for REANALYSIS of old data, figures already up
use_old_fig=1;
if exist('dmin','var') ~=1
    dmin=input('dmin is not saved in your workspace, type what you want dmin to be right now');
end
if exist('plot_thresh','var') ~=1
    plot_thresh=0;
end
en=1;

skipto=0;
[pulses,threshpts,fig_handles]=mznps_pickpulse_semiauto_nodownsamp(ydetrend,yasls,yas2det,dmin,stderror,yas3det,plot_thresh,skipto,use_old_fig,fig_handles,en,pulsesog);


%% run for REANALYSIS of old data, figures already up - START from where you left off 
use_old_fig=1;
if exist('dmin','var') ~=1
    dmin=input('dmin is not saved in your workspace, type what you want dmin to be right now');
end
if exist('plot_thresh','var') ~=1
    plot_thresh=0;
end
en=1;
i=2;
while i<=length(pulses(:,1))
    if pulses(i,1)==0
        i=i-1;
        skipto=pulses(i,1);
        break
    else
        i=i+1;
    end
end

[pulses,threshpts,fig_handles]=mznps_pickpulse_semiauto_nodownsamp(ydetrend,yasls,yas2det,dmin,stderror,yas3det,plot_thresh,skipto,use_old_fig,fig_handles,en,pulsesog);




%% find fig handles if figures are up, but handles aren't saved
%this might happen if it was your first run of the session and it ended in an error 

fa=findobj('type','figure','Name','Data Set');
fb=findobj('type','figure','Name','Entire Event');
f4=findobj('type','figure','Name','Window of Interest');
fig_handles=[fa;fb;f4];
